name: finance_tracker_flutter
description: A Firebase-powered cross-platform finance tracker app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.4
  firebase_auth: ^4.12.1
  path_provider: ^2.0.11
  csv: ^5.0.0
  pdf: ^3.10.4
  printing: ^5.11.0
  intl: ^0.18.1
  fl_chart: ^0.63.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
